version: '2'

services:

### Mount Applications ######################################

    applications:
        image: tianon/true
        volumes:
            - ./:/var/www/html/bradfab.neighborhoods.com

### Bradfab Container (php-fpm) #########################

    bradfab:
        build:
            context: ../Bradfab
            args:
                - COMPOSER_TOKEN=9f506692cafe6be658ce31bcd5e2a481ffb5e884
                - INSTALL_XDEBUG=true
                - COMPOSER_INSTALL=false
        volumes_from:
            - applications
        expose:
            - "9001"
        environment:
            PHP_IDE_CONFIG: "serverName=bradfab.neighborhoods.com"
        extra_hosts:
            - "dockerhost:10.200.10.1"
        dns: 10.200.10.1
