#!/usr/bin/env php
<?php
declare(strict_types=1);
error_reporting(E_ALL);

$PWD = __DIR__;

// Must load autoloader before including any Annotation Processors
if (file_exists($autoloaderFilePath = dirname($PWD, 5) . '/autoload.php')) {
    /** @noinspection PhpIncludeInspection */
    require_once $autoloaderFilePath;
} elseif (file_exists($autoloaderFilePath = dirname($PWD, 3) . '/vendor/autoload.php')) {
    /** @noinspection PhpIncludeInspection */
    require_once $autoloaderFilePath;
} else {
    throw new RuntimeException('Unable to find the Composer autoloader.');
}

// Include Annotation Processors for Buphalo
// None for this test

// Add exec envs
$prefix = 'Neighborhoods_Buphalo_V1';
$namespaceAppBuilder = 'TargetApplication_BuilderInterface';
$namespaceTemplateMapBuilder = 'TemplateTree_Map_Builder_FactoryInterface';

putenv(build_env('TargetApplication_BuilderInterface', 'SourceDirectoryPath', "$PWD/src"));
putenv(build_env('TargetApplication_BuilderInterface', 'FabricationDirectoryPath', "$PWD/fab"));
putenv(build_env('TargetApplication_BuilderInterface', 'NamespacePrefix', "Neighborhoods\\BuphaloTest"));
putenv(
    build_env(
        'TemplateTree_Map_Builder_FactoryInterface',
        'TemplateTreeDirectoryPaths',
        "primary:$PWD/templates/primary,secondary:$PWD/templates/secondary"
    )
);

// Include Buphalo
require_once($PWD . '/../../../bin/v1/buphalo.php');

// Diff the two directories
exec("diff -r $PWD/control/ $PWD/fab/", $output, $return);

if ($return) {
    echo(implode(PHP_EOL, $output) . PHP_EOL);
    die(1);
}

function build_env(string $namespace, string $variable, string $value): string
{
    $prefix = 'Neighborhoods_Buphalo_V1';
    return sprintf('%s_%s__%s=%s', $prefix, $namespace, $variable, $value);
}
