actors:
  <ActorName>/AwareTrait.php:
    template: Actor/AwareTrait.php
  <ActorName>/Factory.php:
    template: Actor/Factory.php
  <ActorName>/Factory.service.yml:
    template: Actor/Factory.service.yml
  <ActorName>/FactoryInterface.php:
    template: Actor/FactoryInterface.php
  <ActorName>/Factory/AwareTrait.php:
    template: Actor/Factory/AwareTrait.php
