name: "Run Tests"

on:
  pull_request:

jobs:
  run_tests:
    name: "Run Tests on PHP ${{ matrix.php_version }}"
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        experimental: [false]
        include:
          - os: ubuntu-18.04
            php_version: '7.2'
          - os: ubuntu-18.04
            php_version: '7.3'
          - os: ubuntu-latest
            php_version: '7.4'
          - os: ubuntu-latest
            php_version: '8.0'
            experimental: true
          - os: ubuntu-latest
            php_version: '8.1'
            experimental: true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          coverage: none

      - name: Install Dependencies
        run: composer install

      - name: Run Tests
        run: tests/run_tests
